/* eslint-disable react-refresh/only-export-components */
import {
  IconActivityHeartbeat,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowDown,
  IconArrowDownRight,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowsExchange,
  IconArrowsMaximize,
  IconBan,
  IconBarcode,
  IconBook,
  IconBolt,
  IconBox,
  IconBrandGithub,
  IconBriefcase,
  IconBuilding,
  IconBuildingBank,
  IconCalculator,
  IconCalendar,
  IconCalendarPlus,
  IconCalendarTime,
  IconCalendarX,
  IconCamera,
  IconCash,
  IconChartBar,
  IconChartLine,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsUp,
  IconCircle,
  IconCircleCheck,
  IconCircleFilled,
  IconCircleMinus,
  IconCirclePlus,
  IconCircleX,
  IconClipboard,
  IconClock,
  IconCloudUpload,
  IconCode,
  IconCompass,
  IconCopy,
  IconCurrencyDollar,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDownload,
  IconExclamationMark,
  IconExternalLink,
  IconEye,
  IconFile,
  IconFileCheck,
  IconFileExport,
  IconFileImport,
  IconFilePencil,
  IconFileSpreadsheet,
  IconFileTypePdf,
  IconFilter,
  IconFilterFilled,
  IconFilterOff,
  IconFlag,
  IconFolderOpen,
  IconGift,
  IconHeadphones,
  IconHeart,
  IconHierarchy,
  IconHistory,
  IconHourglass,
  IconIdBadge2,
  IconInfoCircle,
  IconInbox,
  IconKey,
  IconLibraryPhoto,
  IconLink,
  IconList,
  IconListCheck,
  IconLoader,
  IconLoader2,
  IconLock,
  IconLogin2,
  IconLogout2,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessages,
  IconMicrophone,
  IconMinus,
  IconMoon,
  IconPalette,
  IconPaperclip,
  IconPercentage,
  IconPencil,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconQrcode,
  IconQuestionMark,
  IconRefresh,
  IconRosetteDiscountCheck,
  IconSchool,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShield,
  IconShoppingCart,
  IconSparkles,
  IconSpeakerphone,
  IconSquareCheck,
  IconStarFilled,
  IconStopwatch,
  IconSun,
  IconTable,
  IconTag,
  IconTags,
  IconTarget,
  IconTicket,
  IconTool,
  IconTrash,
  IconTrees,
  IconTruck,
  IconUpload,
  IconUser,
  IconUserEdit,
  IconUserMinus,
  IconUserPlus,
  IconUsers,
  IconVolume,
  IconWallet,
  IconWindowMaximize,
  IconWindowMinimize,
  IconX,
} from "@tabler/icons-react";

import "./app-icon.css";

const ICONS = {
  "activity-heartbeat": IconActivityHeartbeat,
  "adjustments-horizontal": IconAdjustmentsHorizontal,
  "alert-circle": IconAlertCircle,
  "alert-triangle": IconAlertTriangle,
  "arrow-back-up": IconArrowBackUp,
  "arrow-down": IconArrowDown,
  "arrow-down-right": IconArrowDownRight,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up": IconArrowUp,
  "arrow-up-right": IconArrowUpRight,
  "arrows-exchange": IconArrowsExchange,
  "arrows-maximize": IconArrowsMaximize,
  ban: IconBan,
  barcode: IconBarcode,
  book: IconBook,
  bolt: IconBolt,
  box: IconBox,
  "brand-github": IconBrandGithub,
  briefcase: IconBriefcase,
  building: IconBuilding,
  "building-bank": IconBuildingBank,
  calculator: IconCalculator,
  calendar: IconCalendar,
  "calendar-plus": IconCalendarPlus,
  "calendar-time": IconCalendarTime,
  "calendar-x": IconCalendarX,
  camera: IconCamera,
  cash: IconCash,
  "chart-bar": IconChartBar,
  "chart-line": IconChartLine,
  check: IconCheck,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevrons-up": IconChevronsUp,
  circle: IconCircle,
  "circle-check": IconCircleCheck,
  "circle-filled": IconCircleFilled,
  "circle-minus": IconCircleMinus,
  "circle-plus": IconCirclePlus,
  "circle-x": IconCircleX,
  clipboard: IconClipboard,
  clock: IconClock,
  "cloud-upload": IconCloudUpload,
  code: IconCode,
  compass: IconCompass,
  copy: IconCopy,
  "currency-dollar": IconCurrencyDollar,
  database: IconDatabase,
  "device-desktop": IconDeviceDesktop,
  "device-floppy": IconDeviceFloppy,
  download: IconDownload,
  "exclamation-mark": IconExclamationMark,
  "external-link": IconExternalLink,
  eye: IconEye,
  file: IconFile,
  "file-check": IconFileCheck,
  "file-export": IconFileExport,
  "file-import": IconFileImport,
  "file-pencil": IconFilePencil,
  "file-spreadsheet": IconFileSpreadsheet,
  "file-type-pdf": IconFileTypePdf,
  filter: IconFilter,
  "filter-filled": IconFilterFilled,
  "filter-off": IconFilterOff,
  flag: IconFlag,
  "folder-open": IconFolderOpen,
  gift: IconGift,
  headphones: IconHeadphones,
  heart: IconHeart,
  hierarchy: IconHierarchy,
  history: IconHistory,
  hourglass: IconHourglass,
  "id-badge": IconIdBadge2,
  "info-circle": IconInfoCircle,
  inbox: IconInbox,
  key: IconKey,
  "library-photo": IconLibraryPhoto,
  link: IconLink,
  list: IconList,
  "list-check": IconListCheck,
  loader: IconLoader,
  "loader-2": IconLoader2,
  lock: IconLock,
  login: IconLogin2,
  logout: IconLogout2,
  mail: IconMail,
  "map-pin": IconMapPin,
  menu: IconMenu2,
  messages: IconMessages,
  microphone: IconMicrophone,
  minus: IconMinus,
  moon: IconMoon,
  palette: IconPalette,
  paperclip: IconPaperclip,
  percentage: IconPercentage,
  pencil: IconPencil,
  photo: IconPhoto,
  pause: IconPlayerPause,
  play: IconPlayerPlay,
  plus: IconPlus,
  qrcode: IconQrcode,
  question: IconQuestionMark,
  refresh: IconRefresh,
  verified: IconRosetteDiscountCheck,
  school: IconSchool,
  search: IconSearch,
  send: IconSend,
  server: IconServer,
  settings: IconSettings,
  shield: IconShield,
  "shopping-cart": IconShoppingCart,
  sparkles: IconSparkles,
  speakerphone: IconSpeakerphone,
  "square-check": IconSquareCheck,
  "star-filled": IconStarFilled,
  stopwatch: IconStopwatch,
  sun: IconSun,
  table: IconTable,
  tag: IconTag,
  tags: IconTags,
  target: IconTarget,
  ticket: IconTicket,
  tool: IconTool,
  trash: IconTrash,
  trees: IconTrees,
  truck: IconTruck,
  upload: IconUpload,
  user: IconUser,
  "user-edit": IconUserEdit,
  "user-minus": IconUserMinus,
  "user-plus": IconUserPlus,
  users: IconUsers,
  volume: IconVolume,
  wallet: IconWallet,
  "window-maximize": IconWindowMaximize,
  "window-minimize": IconWindowMinimize,
};

const LEGACY_NAMES = {
  "angle-double-up": "chevrons-up",
  "angle-left": "chevron-left",
  "angle-right": "chevron-right",
  "arrow-right-arrow-left": "arrows-exchange",
  "arrows-alt": "arrows-maximize",
  bars: "menu",
  "building-columns": "building-bank",
  "bullseye": "target",
  "calendar-clock": "calendar-time",
  "calendar-times": "calendar-x",
  "chart-bar": "chart-bar",
  "chart-line": "chart-line",
  "check-circle": "circle-check",
  "check-square": "square-check",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "circle-fill": "circle-filled",
  "clone": "copy",
  "cog": "settings",
  "comments": "messages",
  "dollar": "currency-dollar",
  desktop: "device-desktop",
  "envelope": "mail",
  "exclamation": "exclamation-mark",
  "exclamation-circle": "alert-circle",
  "exclamation-triangle": "alert-triangle",
  "file-edit": "file-pencil",
  "file-excel": "file-spreadsheet",
  "file-pdf": "file-type-pdf",
  "filter-fill": "filter-filled",
  "filter-slash": "filter-off",
  "github": "brand-github",
  "graduation-cap": "school",
  "id-card": "id-badge",
  "image": "photo",
  "images": "library-photo",
  "map-marker": "map-pin",
  "megaphone": "speakerphone",
  "minus-circle": "circle-minus",
  "money-bill": "cash",
  "pause-circle": "pause",
  "plus-circle": "circle-plus",
  "question-circle": "question",
  "save": "device-floppy",
  "sign-in": "login",
  "sign-out": "logout",
  "sitemap": "hierarchy",
  "sliders-h": "adjustments-horizontal",
  "spinner": "loader-2",
  "spinner-dotted": "loader",
  "star-fill": "star-filled",
  "sync": "refresh",
  "times": "x",
  "times-circle": "circle-x",
  "tree": "trees",
  "undo": "arrow-back-up",
  "verified": "verified",
  "volume-up": "volume",
  "wave-pulse": "activity-heartbeat",
  "wrench": "tool",
};

const ICONS_WITH_ALIASES = {
  ...ICONS,
  x: IconX,
};

export function normalizeIconName(value) {
  const tokens = String(value || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const token = tokens.find((item) => item.startsWith("pi-")) || tokens[0] || "question";
  const rawName = token.replace(/^pi-/, "");
  return LEGACY_NAMES[rawName] || rawName;
}

export function AppIcon({
  name,
  icon,
  size = "1.5em",
  stroke = 1.2,
  className = "",
  spin = false,
  title,
  ...props
}) {
  const source = name || icon || "question";
  const normalizedName = normalizeIconName(source);
  const Icon = ICONS_WITH_ALIASES[normalizedName] || IconQuestionMark;
  const shouldSpin = spin || String(source).includes("pi-spin");

  return (
    <Icon
      size={size}
      stroke={stroke}
      className={`tm-icon ${shouldSpin ? "tm-icon--spin" : ""} ${className}`.trim()}
      aria-hidden={title ? undefined : true}
      aria-label={title || undefined}
      role={title ? "img" : undefined}
      {...props}
    >
      {title ? <title>{title}</title> : null}
    </Icon>
  );
}

export function appIcon(name, props = {}) {
  return <AppIcon name={name} {...props} />;
}
