name: Atualização para o TM HUB - Front End
on: # Call event
  push: # This is a PUSH event listener
    branches: [ "main" ] 

jobs: # Jobs will run
  deploy: # This a deploy 
    runs-on: 
      ubuntu-latest # This is a RUN on Ubuntu (LINUX)

    steps: # And this is steps for Deploy!
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            nvm use 24

            cd /home/guibs/tmhub

            git stash
            git pull origin main

            node -v
            npm -v

            npm install
            npm run build
